# Generated by Django 4.2.30 on 2026-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='av_cpy',
            field=models.IntegerField(),
        ),
    ]
