# Generated by Django 6.0.5 on 2026-05-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ph_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(max_length=100),
        ),
    ]
